// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbIDYW0B4D3TROH8ScUZDSUeSexAF4t2U',
    appId: '1:124788210960:web:48239ff576d9cd03cf7995',
    messagingSenderId: '124788210960',
    projectId: 'authexample1-609be',
    authDomain: 'authexample1-609be.firebaseapp.com',
    storageBucket: 'authexample1-609be.firebasestorage.app',
    measurementId: 'G-8NZJSSZQT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKb5k5sj5CY01xScLCKr-uSlyP7tNwXY',
    appId: '1:124788210960:android:92f156690f3aa7f2cf7995',
    messagingSenderId: '124788210960',
    projectId: 'authexample1-609be',
    storageBucket: 'authexample1-609be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuEeaVugU2NMb1SoUbmw-HMaW-qkaUHvg',
    appId: '1:124788210960:ios:743ecfb177366e0ccf7995',
    messagingSenderId: '124788210960',
    projectId: 'authexample1-609be',
    storageBucket: 'authexample1-609be.firebasestorage.app',
    iosClientId: '124788210960-715uifbt64ka6cduep8kn96t90ftjs7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuEeaVugU2NMb1SoUbmw-HMaW-qkaUHvg',
    appId: '1:124788210960:ios:743ecfb177366e0ccf7995',
    messagingSenderId: '124788210960',
    projectId: 'authexample1-609be',
    storageBucket: 'authexample1-609be.firebasestorage.app',
    iosClientId: '124788210960-715uifbt64ka6cduep8kn96t90ftjs7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbIDYW0B4D3TROH8ScUZDSUeSexAF4t2U',
    appId: '1:124788210960:web:49596a5ee2fe4ffccf7995',
    messagingSenderId: '124788210960',
    projectId: 'authexample1-609be',
    authDomain: 'authexample1-609be.firebaseapp.com',
    storageBucket: 'authexample1-609be.firebasestorage.app',
    measurementId: 'G-GSTDQSEB70',
  );
}
